# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deprecated_forms/form_v0.0.3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt5 import QtCore, QtWidgets
from PyQt5.QtWidgets import QInputDialog
from PyQt5.QtCore import QTimer
import random
import server as serv
import logging

#tread for comminication with arduino
class MyThread(QtCore.QThread):
    mysignal = QtCore.pyqtSignal(str)
    def  __init__(self, parent=None):
        QtCore.QThread.__init__(self, parent)
        self.server = serv.port()
        self.data = None

    def run(self):
        self.data = self.server.recv()

    def set_targets(self):
        self.server.send(self.data)



class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(786, 600)
        MainWindow.setStyleSheet("background-color: rgb(212, 214, 232);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 800, 180))
        self.frame.setStyleSheet("background-color: rgb(236, 235, 244);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.unit_lablel_0 = QtWidgets.QTextBrowser(self.frame)
        self.unit_lablel_0.setGeometry(QtCore.QRect(100, 10, 120, 30))
        self.unit_lablel_0.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.unit_lablel_0.setFrameShape(QtWidgets.QFrame.Box)
        self.unit_lablel_0.setObjectName("unit_lablel_0")
        self.current_value_0 = QtWidgets.QTextBrowser(self.frame)
        self.current_value_0.setGeometry(QtCore.QRect(80, 50, 160, 60))
        self.current_value_0.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.current_value_0.setFrameShape(QtWidgets.QFrame.Box)
        self.current_value_0.setObjectName("current_value_0")
        self.target_value_0 = QtWidgets.QTextBrowser(self.frame)
        self.target_value_0.setGeometry(QtCore.QRect(90, 120, 141, 31))
        self.target_value_0.setStyleSheet("background-color: rgb(5, 13, 152);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Carlito\";")
        self.target_value_0.setFrameShape(QtWidgets.QFrame.Box)
        self.target_value_0.setObjectName("target_value_0")
        self.unit_label_1 = QtWidgets.QTextBrowser(self.frame)
        self.unit_label_1.setGeometry(QtCore.QRect(570, 10, 120, 30))
        self.unit_label_1.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.unit_label_1.setFrameShape(QtWidgets.QFrame.Box)
        self.unit_label_1.setObjectName("unit_label_1")
        self.current_value_1 = QtWidgets.QTextBrowser(self.frame)
        self.current_value_1.setGeometry(QtCore.QRect(550, 50, 160, 60))
        self.current_value_1.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.current_value_1.setFrameShape(QtWidgets.QFrame.Box)
        self.current_value_1.setObjectName("current_value_1")
        self.target_value_1 = QtWidgets.QTextBrowser(self.frame)
        self.target_value_1.setGeometry(QtCore.QRect(560, 120, 141, 31))
        self.target_value_1.setStyleSheet("background-color: rgb(5, 13, 152);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Carlito\";")
        self.target_value_1.setFrameShape(QtWidgets.QFrame.Box)
        self.target_value_1.setObjectName("target_value_1")
        self.progressBar = QtWidgets.QProgressBar(self.frame)
        self.progressBar.setGeometry(QtCore.QRect(350, 10, 118, 23))
        self.progressBar.setProperty("value", 99)
        self.progressBar.setObjectName("progressBar")
        self.pitotUnitButton = QtWidgets.QPushButton(self.frame)
        self.pitotUnitButton.setGeometry(QtCore.QRect(30, 10, 30, 30))
        self.pitotUnitButton.setStyleSheet("border-radius : 15; \n"
"  border : 2px solid black;\n"
"background-color: rgb(31, 39, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pitotUnitButton.setObjectName("pitotUnitButton")
        self.pitotTragetButton = QtWidgets.QPushButton(self.frame)
        self.pitotTragetButton.setGeometry(QtCore.QRect(20, 120, 30, 30))
        self.pitotTragetButton.setStyleSheet("border-radius : 15; \n"
"  border : 2px solid black;\n"
"background-color: rgb(31, 39, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pitotTragetButton.setObjectName("pitotTragetButton")
        self.staticUnitButton = QtWidgets.QPushButton(self.frame)
        self.staticUnitButton.setGeometry(QtCore.QRect(730, 10, 30, 30))
        self.staticUnitButton.setStyleSheet("border-radius : 15; \n"
"  border : 2px solid black;\n"
"background-color: rgb(31, 39, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.staticUnitButton.setObjectName("staticUnitButton")
        self.staticTargetButton = QtWidgets.QPushButton(self.frame)
        self.staticTargetButton.setGeometry(QtCore.QRect(730, 120, 30, 30))
        self.staticTargetButton.setStyleSheet("border-radius : 15; \n"
"  border : 2px solid black;\n"
"background-color: rgb(31, 39, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.staticTargetButton.setObjectName("staticTargetButton")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(0, 180, 800, 180))
        self.frame_2.setStyleSheet("background-color: rgb(246, 245, 244);\n"
"background-color: rgb(153, 193, 241);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.unit_label_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.unit_label_2.setGeometry(QtCore.QRect(100, 10, 120, 30))
        self.unit_label_2.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.unit_label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.unit_label_2.setObjectName("unit_label_2")
        self.current_value_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.current_value_2.setGeometry(QtCore.QRect(80, 50, 160, 60))
        self.current_value_2.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.current_value_2.setFrameShape(QtWidgets.QFrame.Box)
        self.current_value_2.setObjectName("current_value_2")
        self.target_value_2 = QtWidgets.QTextBrowser(self.frame_2)
        self.target_value_2.setGeometry(QtCore.QRect(90, 120, 141, 31))
        self.target_value_2.setStyleSheet("background-color: rgb(5, 13, 152);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Carlito\";")
        self.target_value_2.setFrameShape(QtWidgets.QFrame.Box)
        self.target_value_2.setObjectName("target_value_2")
        self.unit_label_3 = QtWidgets.QTextBrowser(self.frame_2)
        self.unit_label_3.setGeometry(QtCore.QRect(570, 10, 120, 30))
        self.unit_label_3.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.unit_label_3.setFrameShape(QtWidgets.QFrame.Box)
        self.unit_label_3.setObjectName("unit_label_3")
        self.current_value_3 = QtWidgets.QTextBrowser(self.frame_2)
        self.current_value_3.setGeometry(QtCore.QRect(550, 50, 160, 60))
        self.current_value_3.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.current_value_3.setFrameShape(QtWidgets.QFrame.Box)
        self.current_value_3.setObjectName("current_value_3")
        self.target_value_3 = QtWidgets.QTextBrowser(self.frame_2)
        self.target_value_3.setGeometry(QtCore.QRect(560, 120, 141, 31))
        self.target_value_3.setStyleSheet("background-color: rgb(5, 13, 152);\n"
"border-color: rgb(0, 0, 0);\n"
"color: rgb(255, 255, 255);\n"
"font: 75 11pt \"Carlito\";")
        self.target_value_3.setFrameShape(QtWidgets.QFrame.Box)
        self.target_value_3.setObjectName("target_value_3")
        self.pitotRateTargetButton = QtWidgets.QPushButton(self.frame_2)
        self.pitotRateTargetButton.setGeometry(QtCore.QRect(20, 120, 30, 30))
        self.pitotRateTargetButton.setStyleSheet("border-radius : 15; \n"
"  border : 2px solid black;\n"
"background-color: rgb(31, 39, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pitotRateTargetButton.setObjectName("pitotRateTargetButton")
        self.staticRateTargetButton = QtWidgets.QPushButton(self.frame_2)
        self.staticRateTargetButton.setGeometry(QtCore.QRect(730, 120, 30, 30))
        self.staticRateTargetButton.setStyleSheet("border-radius : 15; \n"
"  border : 2px solid black;\n"
"background-color: rgb(31, 39, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.staticRateTargetButton.setObjectName("staticRateTargetButton")
        self.message_space = QtWidgets.QTextEdit(self.centralwidget)
        self.message_space.setGeometry(QtCore.QRect(260, 410, 270, 131))
        self.message_space.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.message_space.setFrameShape(QtWidgets.QFrame.Box)
        self.message_space.setObjectName("message_space")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(260, 380, 270, 20))
        self.label.setStyleSheet("\n"
"font: 75 11pt \"Carlito\";\n"
"color:rgb(0, 0, 250)")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setTextFormat(QtCore.Qt.PlainText)
        self.label.setObjectName("label")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(0, 360, 240, 90))
        self.frame_3.setStyleSheet("background-color: rgb(53, 132, 228);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.textBrowser_21 = QtWidgets.QTextBrowser(self.frame_3)
        self.textBrowser_21.setGeometry(QtCore.QRect(50, 10, 131, 51))
        self.textBrowser_21.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.textBrowser_21.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_21.setObjectName("textBrowser_21")
        self.pitotModeButton = QtWidgets.QPushButton(self.frame_3)
        self.pitotModeButton.setGeometry(QtCore.QRect(10, 10, 30, 30))
        self.pitotModeButton.setStyleSheet("border-radius : 15; \n"
"  border : 2px solid black;\n"
"background-color: rgb(31, 39, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.pitotModeButton.setObjectName("pitotModeButton")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(550, 360, 240, 90))
        self.frame_4.setStyleSheet("background-color: rgb(53, 132, 228);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.textBrowser_20 = QtWidgets.QTextBrowser(self.frame_4)
        self.textBrowser_20.setGeometry(QtCore.QRect(50, 10, 131, 51))
        self.textBrowser_20.setStyleSheet("background-color: rgb(255, 163, 72);\n"
"border-color: rgb(0, 0, 0);\n"
"font: 75 11pt \"Carlito\";")
        self.textBrowser_20.setFrameShape(QtWidgets.QFrame.Box)
        self.textBrowser_20.setObjectName("textBrowser_20")
        self.staticModeButton = QtWidgets.QPushButton(self.frame_4)
        self.staticModeButton.setGeometry(QtCore.QRect(190, 10, 30, 30))
        self.staticModeButton.setStyleSheet("border-radius : 15; \n"
"  border : 2px solid black;\n"
"background-color: rgb(31, 39, 156);\n"
"color: rgb(255, 255, 255);\n"
"")
        self.staticModeButton.setObjectName("staticModeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 786, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        #start thread for measure recieving
        self.my_thread = MyThread()
        self.my_thread.start()
        self.my_thread.finished.connect(self.on_finished)
        self.start_selection()

        #add target button functional
        self.pitotTragetButton.clicked.connect(lambda: self.set_target(self.pitotTragetButton.objectName()))
        self.pitotRateTargetButton.clicked.connect(lambda: self.set_target(self.pitotRateTargetButton.objectName()))
        self.staticTargetButton.clicked.connect(lambda: self.set_target(self.staticTargetButton.objectName()))
        self.staticRateTargetButton.clicked.connect(lambda: self.set_target(self.staticRateTargetButton.objectName()))

        self.target_map = {self.pitotTragetButton.objectName() : 0.0, \
                           self.pitotRateTargetButton.objectName() : 0.0, \
                           self.staticTargetButton.objectName(): 0.0,
                           self.staticRateTargetButton.objectName(): 0.0}
        self.target_values = {self.pitotTragetButton.objectName() : self.target_value_0, \
                           self.pitotRateTargetButton.objectName() : self.target_value_2, \
                           self.staticTargetButton.objectName(): self.target_value_1,
                           self.staticRateTargetButton.objectName(): self.target_value_3}
        
        logging.basicConfig(level=logging.INFO, filename="logger.log",filemode="w",
                    format="%(asctime)s %(levelname)s %(message)s")



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Messages"))

    def set_target(self, caller):
        print(caller)
        text, ok = QInputDialog.getText(self.centralwidget, caller,
            f'Enter value {caller}:')

        if ok:
            self.target_values[caller].setText(text)
            self.target_map[caller] = float(text)
            #print(self.target_map)
            self.my_thread.data = self.target_map
            self.my_thread.set_targets()

    def start_selection(self):
        # Repeating timer, calls random_pick over and over.
        self.picktimer = QTimer()
        self.picktimer.setInterval(500)
        self.picktimer.timeout.connect(self.my_thread.start)
        self.picktimer.start()

    def set_new_data(self, data):
        measurements = [x for x in data.split()]
        print(measurements)
        
        self.current_value_0.setText(measurements[0])
        self.current_value_1.setText(measurements[1])
        self.current_value_2.setText(measurements[2])
        self.current_value_3.setText(measurements[3])
        logging.info(f'measurements: {" ".join(measurements)} \
                     targets: {" ".join(self.my_thread.data.items())}')
        
        #self.progressBar.setValue(random.randint(0, 100)) # <- you may edit power level
        self.progressBar.setValue(99)

    def on_finished(self):      # Вызывается при завершении потока
        self.new_data = self.my_thread.data
        self.set_new_data(self.new_data)

    def closeEvent(self, event):
        self.my_thread.server.close()


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pitotUnitButton.setText(_translate("MainWindow", "1"))
        self.pitotTragetButton.setText(_translate("MainWindow", "2"))
        self.staticUnitButton.setText(_translate("MainWindow", " 5"))
        self.staticTargetButton.setText(_translate("MainWindow", "6"))
        self.pitotRateTargetButton.setText(_translate("MainWindow", "3"))
        self.staticRateTargetButton.setText(_translate("MainWindow", "7"))
        self.label.setText(_translate("MainWindow", "Messages"))
        self.pitotModeButton.setText(_translate("MainWindow", "4"))
        self.staticModeButton.setText(_translate("MainWindow", "8"))
